import { Router, type Request, type Response, type NextFunction } from 'express';
import { z } from 'zod';
import { HandoffService } from '../application/handoff.js';
import { RunService } from '../application/runs.js';
import { getActor } from '../application/security.js';

export const handoffRouter = Router();
const handoffs = new HandoffService();
const runs = new RunService();
const route = (action: (req: Request) => Promise<unknown>) => async (req: Request, res: Response, next: NextFunction) => { try { res.json({ data: await action(req), error: null }); } catch (error) { next(error); } };
handoffRouter.get('/handoffs', route((req) => handoffs.list(getActor(req), typeof req.query.taskId === 'string' ? req.query.taskId : undefined)));
handoffRouter.post('/handoffs', route((req) => handoffs.prepare(getActor(req), req.body)));
handoffRouter.get('/handoffs/:id', route((req) => handoffs.get(getActor(req), String(req.params.id))));
handoffRouter.patch('/handoffs/:id', route((req) => handoffs.revise(getActor(req), String(req.params.id), req.body)));
handoffRouter.post('/handoffs/:id/claim', route((req) => handoffs.claim(getActor(req), String(req.params.id), req.body)));
handoffRouter.post('/handoffs/:id/start', route((req) => runs.start(getActor(req), String(req.params.id), req.body)));
handoffRouter.post('/handoffs/:id/cancel', route((req) => handoffs.cancel(getActor(req), String(req.params.id))));
handoffRouter.post('/handoffs/:id/review', route((req) => handoffs.review(getActor(req), String(req.params.id), req.body)));
handoffRouter.get('/runners/capabilities', route((req) => runs.capabilities(getActor(req))));
handoffRouter.get('/runs/:id', route((req) => runs.get(getActor(req), String(req.params.id))));
handoffRouter.get('/runs/:id/events', route((req) => runs.events(getActor(req), String(req.params.id), z.coerce.number().int().min(0).default(0).parse(req.query.afterSequence))));
handoffRouter.post('/runs/:id/report', route((req) => runs.report(getActor(req), String(req.params.id), req.body)));
handoffRouter.post('/runs/:id/progress', route((req) => runs.progress(getActor(req), String(req.params.id), req.body)));
handoffRouter.post('/runs/:id/continue', route((req) => runs.continue(getActor(req), String(req.params.id), req.body)));
handoffRouter.post('/runs/:id/reconcile', route((req) => runs.reconcile(getActor(req), String(req.params.id))));
handoffRouter.post('/runs/:id/cancel', route((req) => runs.cancel(getActor(req), String(req.params.id))));
handoffRouter.post('/runs/:id/confirm-stopped', route((req) => runs.confirmStopped(getActor(req), String(req.params.id), req.body)));
handoffRouter.post('/runs/:id/proposals', route((req) => runs.prepareProposals(getActor(req), String(req.params.id))));
handoffRouter.get('/runs/:id/artifacts', route((req) => runs.artifacts(getActor(req), String(req.params.id))));
handoffRouter.post('/runs/:id/apply', route((req) => runs.apply(getActor(req), String(req.params.id), req.body)));
handoffRouter.get('/artifacts/:id/content', route((req) => runs.artifactContent(getActor(req), String(req.params.id))));
