import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api.js';
import { json, operationNames, parseStored, usePlatformAction, type Command } from '@/lib/platform.js';
import { Button } from '@/components/ui/button.js';
import { Input } from '@/components/ui/input.js';
import { Textarea } from '@/components/ui/textarea.js';

type Proposal = { id: string; status: string; revision: number; actorId: string; commands: Command[] | string; preview: unknown; createdAt: string };
const labels: Record<string, string> = { title: '标题', name: '名称', description: '说明', content: '内容', dueDate: '截止日期', priority: '优先级', status: '状态', resultSummary: '结果摘要', reason: '理由' };
export function ProposalsPage() {
  const [status, setStatus] = useState('pending');
  const query = useQuery({ queryKey: ['proposals', status], queryFn: () => api<Proposal[]>(`/api/v1/proposals?status=${status}`) });
  return <section className="mx-auto max-w-4xl space-y-5 p-5 sm:p-7"><header className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-semibold">待确认</h1><p className="mt-2 text-sm text-muted-foreground">检查业务改动和依据后再应用。存在依赖的修改会一起提交。</p></div><select className="glass-control h-10 rounded-lg px-3" aria-label="提议状态" value={status} onChange={(event) => setStatus(event.target.value)}><option value="pending">待确认</option><option value="applied">已执行</option><option value="rejected">已拒绝</option></select></header>{query.error && <p role="alert">{query.error.message}</p>}{query.isLoading ? <p>正在加载…</p> : !query.data?.length ? <p className="py-8 text-sm text-muted-foreground">暂无此状态的提议。</p> : query.data.map((proposal) => <ProposalCard key={`${proposal.id}:${proposal.revision}`} proposal={proposal} />)}</section>;
}
function ProposalCard({ proposal }: { proposal: Proposal }) {
  const original = parseStored<Command[]>(proposal.commands, []);
  const [commands, setCommands] = useState(original);
  const { run, busy } = usePlatformAction();
  const preview = parseStored<any[]>(proposal.preview as any, []);
  const dirty = json(original) !== json(commands);
  const change = (index: number, key: string, value: unknown) => setCommands((all) => all.map((command, i) => i === index ? { ...command, input: { ...command.input, [key]: value } } : command));
  return <article className="glass-subtle space-y-4 rounded-xl p-4"><div className="flex flex-wrap justify-between gap-2 text-xs text-muted-foreground"><span>来自 {proposal.actorId}</span><time>{new Date(proposal.createdAt).toLocaleString()}</time></div>{commands.map((command, index) => <div key={index} className="space-y-3 border-t pt-3"><h2 className="font-semibold">{operationNames[command.kind] ?? command.kind.replace(/_/g, ' ')}{command.targetId && <span className="ml-2 text-xs font-normal text-muted-foreground">{command.targetId}</span>}</h2>{preview[index]?.detail?.before && <p className="text-xs text-muted-foreground">原内容：{preview[index].detail.before.title ?? preview[index].detail.before.name ?? ''} · 版本 {preview[index].detail.before.revision}</p>}{Object.entries(command.input ?? {}).map(([key, value]) => labels[key] && (typeof value === 'string' || value === null) ? <label className="block text-sm" key={key}>{labels[key]}{['description', 'content', 'resultSummary'].includes(key) ? <Textarea className="mt-1" value={String(value ?? '')} disabled={proposal.status !== 'pending'} onChange={(event) => change(index, key, event.target.value)} /> : <Input className="mt-1" type={key === 'dueDate' ? 'date' : 'text'} value={String(value ?? '')} disabled={proposal.status !== 'pending'} onChange={(event) => change(index, key, key === 'dueDate' ? event.target.value || null : event.target.value)} />}</label> : <p className="break-all text-sm text-muted-foreground" key={key}>{key}：{Array.isArray(value) ? value.join('、') : typeof value === 'object' ? '附有来源与关联信息' : String(value)}</p>)}</div>)}<div className="space-y-2 text-xs text-muted-foreground">{preview.map((item, index) => <p key={index}>涉及任务：{item.detail?.affectedTasks?.map((task: any) => `${task.title}（版本 ${task.revision}）`).join('、') || '按上方内容更新对应对象'}</p>)}</div><details><summary className="cursor-pointer text-sm text-muted-foreground">依据与影响范围</summary><pre className="mt-2 max-h-64 overflow-auto whitespace-pre-wrap break-all text-xs">{typeof proposal.preview === 'string' ? proposal.preview : JSON.stringify(proposal.preview, null, 2)}</pre></details>{proposal.status === 'pending' && <div className="flex flex-wrap justify-end gap-2"><Button variant="ghost" disabled={busy} onClick={() => void run(() => api(`/api/v1/proposals/${proposal.id}/reject`, { method: 'POST', body: json({ expectedRevision: proposal.revision }) }), '已拒绝')}>拒绝</Button>{dirty ? <Button disabled={busy} onClick={() => void run(() => api(`/api/v1/proposals/${proposal.id}`, { method: 'PATCH', body: json({ expectedRevision: proposal.revision, commands }) }), '已更新提议，请检查后确认')}>保存调整并重新预览</Button> : <Button disabled={busy} onClick={() => void run(() => api(`/api/v1/proposals/${proposal.id}/approve`, { method: 'POST', body: json({ expectedRevision: proposal.revision, requestId: crypto.randomUUID() }) }), '改动已应用')}>确认整组修改</Button>}</div>}</article>;
}
