import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api, type Topic } from '@/lib/api.js';
import { json, parseStored, usePlatformAction } from '@/lib/platform.js';
import { Button } from '@/components/ui/button.js';
import { Input } from '@/components/ui/input.js';

export function ReviewsPage({ topics }: { topics: Topic[] }) {
  const rules = useQuery({ queryKey: ['review-rules'], queryFn: () => api<any[]>('/api/v1/reviews/rules') });
  const batches = useQuery({ queryKey: ['review-batches'], queryFn: () => api<any[]>('/api/v1/reviews/batches'), refetchInterval: 30_000 });
  const [editing, setEditing] = useState<any>(null);
  const [name, setName] = useState('');
  const [frequency, setFrequency] = useState('daily');
  const [timeOfDay, setTime] = useState('21:00');
  const [timeZone, setZone] = useState(Intl.DateTimeFormat().resolvedOptions().timeZone);
  const [weekDay, setDay] = useState(0);
  const [selected, setSelected] = useState<string[]>([]);
  const [inbox, setInbox] = useState(true);
  const [provider, setProvider] = useState('none');
  const { run, busy } = usePlatformAction();
  return <section className="mx-auto max-w-5xl space-y-6 p-5 sm:p-7"><header><h1 className="text-2xl font-semibold">定期回顾</h1><p className="mt-2 text-sm text-muted-foreground">整理任务变化和资料，生成待确认建议。规则启用后，在本机服务运行期间执行。</p></header>
    <form className="glass-subtle space-y-4 rounded-xl p-4" onSubmit={(event) => { event.preventDefault(); void run(async () => { const result = await api(editing ? `/api/v1/reviews/rules/${editing.id}` : '/api/v1/reviews/rules', { method: editing ? 'PATCH' : 'POST', body: json({ name, enabled: editing?.enabled ?? false, frequency, timeOfDay, timeZone, weekDay, topicIds: selected, includeInbox: inbox, provider, ...(editing ? { expectedVersion: editing.revision } : {}) }) }); setName(''); setEditing(null); return result; }, '规则已保存，可预览后启用'); }}>
      <h2 className="font-semibold">{editing ? '编辑回顾规则' : '新建回顾规则'}</h2><Input aria-label="回顾名称" placeholder="例如：每周项目回顾" value={name} onChange={(event) => setName(event.target.value)} required />
      <div className="flex flex-wrap gap-3"><select className="glass-control h-10 rounded-lg px-3 text-sm" aria-label="回顾频率" value={frequency} onChange={(event) => setFrequency(event.target.value)}><option value="daily">每日</option><option value="weekly">每周</option></select>{frequency === 'weekly' && <select className="glass-control h-10 rounded-lg px-3 text-sm" aria-label="回顾星期" value={weekDay} onChange={(event) => setDay(Number(event.target.value))}>{['日', '一', '二', '三', '四', '五', '六'].map((day, index) => <option key={index} value={index}>星期{day}</option>)}</select>}<Input aria-label="回顾时间" className="w-32" type="time" value={timeOfDay} onChange={(event) => setTime(event.target.value)} required /><Input aria-label="回顾时区" className="w-56" value={timeZone} onChange={(event) => setZone(event.target.value)} required /></div>
      <fieldset className="flex flex-wrap gap-4"><legend className="mb-2 text-sm">回顾范围</legend><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={inbox} onChange={(event) => setInbox(event.target.checked)} />收集箱</label>{topics.map((topic) => <label key={topic.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={selected.includes(topic.id)} onChange={(event) => setSelected(event.target.checked ? [...selected, topic.id] : selected.filter((id) => id !== topic.id))} />{topic.name}</label>)}</fieldset>
      <select className="glass-control h-10 max-w-full rounded-lg px-3 text-sm" aria-label="回顾整理方式" value={provider} onChange={(event) => setProvider(event.target.value)}><option value="none">基础回顾（无需模型）</option><option value="builtin">基础回顾 + 内置模型建议</option><option value="external">基础回顾 + 外部 AI 待整理请求</option><option value="codex">基础回顾 + Codex 受限整理</option><option value="claude">基础回顾 + Claude Code 受限整理</option></select>
      <div><Button disabled={busy || !name.trim() || (!inbox && !selected.length)}>保存规则</Button>{editing && <Button type="button" variant="ghost" onClick={() => { setEditing(null); setName(''); }}>取消编辑</Button>}</div>
    </form>
    {(rules.error || batches.error) && <p role="alert">{(rules.error ?? batches.error)?.message}</p>}
    <div className="space-y-3">{rules.data?.map((rule) => <article className="glass-subtle space-y-3 rounded-xl p-4" key={rule.id}><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">{rule.name}</h2><span className="text-xs text-muted-foreground">{rule.enabled ? '已启用' : '已暂停'} · {rule.frequency === 'daily' ? '每日' : '每周'} {rule.timeOfDay} · {rule.timeZone}</span></div><p className="text-xs text-muted-foreground">{[...(rule.includeInbox ? ['收集箱'] : []), ...parseStored<string[]>(rule.topicIds, []).map((id) => topics.find((topic) => topic.id === id)?.name ?? id)].join('、')}</p><div className="flex flex-wrap gap-2"><Button size="sm" variant="ghost" disabled={busy} onClick={() => { setEditing(rule); setName(rule.name); setFrequency(rule.frequency); setTime(rule.timeOfDay); setZone(rule.timeZone); setDay(rule.weekDay); setSelected(parseStored(rule.topicIds, [])); setInbox(rule.includeInbox); setProvider(rule.provider); }}>编辑规则</Button><Button size="sm" variant="outline" disabled={busy} onClick={() => void run(() => api(`/api/v1/reviews/rules/${rule.id}`, { method: 'PATCH', body: json({ expectedVersion: rule.revision, enabled: !rule.enabled }) }), rule.enabled ? '已暂停后续回顾' : '回顾规则已启用')}>{rule.enabled ? '暂停' : '启用'}</Button><Button size="sm" variant="ghost" disabled={busy} onClick={() => void run(() => api(`/api/v1/reviews/rules/${rule.id}/run`, { method: 'POST', body: '{}' }), '回顾已生成')}>立即生成回顾</Button></div></article>)}</div>
    <section className="space-y-3"><h2 className="text-lg font-semibold">已保存的回顾</h2>{!batches.data?.length && <p className="text-sm text-muted-foreground">暂无回顾。</p>}{batches.data?.map((batch) => <details className="glass-subtle rounded-xl p-4" key={batch.id}><summary className="cursor-pointer text-sm">{rules.data?.find((rule) => rule.id === batch.ruleId)?.name ?? '项目回顾'} · {new Date(batch.createdAt).toLocaleString()} · {batch.status === 'ready' ? '已保存' : batch.status === 'partial' ? 'AI 整理待完成' : batch.status}</summary><pre className="my-4 whitespace-pre-wrap text-sm leading-relaxed">{batch.content}</pre>{batch.error && <p role="alert" className="text-xs text-destructive">{batch.error}</p>}{batch.status === 'partial' && <Button size="sm" variant="outline" disabled={busy} onClick={() => void run(() => api(`/api/v1/reviews/batches/${batch.id}/retry`, { method: 'POST', body: '{}' }), '已重新准备整理')}>重试 AI 整理</Button>}{parseStored<string[]>(batch.organizationIds, []).length > 0 && <p className="mt-3 text-xs text-muted-foreground">整理结果保留在项目资料中，候选内容进入待确认。</p>}</details>)}</section>
  </section>;
}
