import express from 'express'; import cors from 'cors'; import { z } from 'zod'; import { TopicService, TaskService } from './services.js'; import { AgentService } from './agent.js';
export const app=express(); app.use(cors()); app.use(express.json()); const topics=new TopicService(), tasks=new TaskService(), agent=new AgentService();
const send=(res:any,data:any)=>res.json({data,error:null}); const schema=(s:any)=>(req:any,res:any,next:any)=>{const r=s.safeParse(req.body); if(!r.success)return res.status(400).json({data:null,error:r.error.flatten()}); req.body=r.data; next();};
app.get('/api/topics',async(_,res,next)=>{try{send(res,await topics.list())}catch(e){next(e)}}); app.get('/api/topics/:id',async(req,res,next)=>{try{const x=await topics.get(req.params.id); if(!x)return res.status(404).json({data:null,error:'主题不存在'}); send(res,x)}catch(e){next(e)}});
app.post('/api/topics',schema(z.object({name:z.string().min(1),description:z.string().optional(),isExploration:z.boolean().optional()})),async(req,res,next)=>{try{send(res,await topics.create(req.body))}catch(e){next(e)}}); app.patch('/api/topics/:id',schema(z.object({name:z.string().min(1).optional(),description:z.string().optional(),isExploration:z.boolean().optional()})),async(req,res,next)=>{try{send(res,await topics.update(req.params.id,req.body))}catch(e){next(e)}}); app.delete('/api/topics/:id',async(req,res,next)=>{try{send(res,await topics.remove(req.params.id))}catch(e){next(e)}});
app.get('/api/tasks',async(req,res,next)=>{try{send(res,await tasks.list(typeof req.query.topicId==='string'?req.query.topicId:undefined))}catch(e){next(e)}}); app.get('/api/tasks/:id',async(req,res,next)=>{try{const x=await tasks.get(req.params.id); if(!x)return res.status(404).json({data:null,error:'任务不存在'}); send(res,x)}catch(e){next(e)}});
const taskBody=z.object({topicId:z.string().min(1),title:z.string().min(1),description:z.string().optional(),status:z.enum(['todo','doing','blocked','done']).optional(),resultSummary:z.string().optional()}); app.post('/api/tasks',schema(taskBody),async(req,res,next)=>{try{send(res,await tasks.create(req.body))}catch(e){next(e)}}); app.patch('/api/tasks/:id',schema(taskBody.partial()),async(req,res,next)=>{try{send(res,await tasks.update(req.params.id,req.body))}catch(e){next(e)}}); app.delete('/api/tasks/:id',async(req,res,next)=>{try{send(res,await tasks.remove(req.params.id))}catch(e){next(e)}});
const chatBody=z.object({conversationId:z.string().optional(),message:z.string().min(1),pageContext:z.object({topicId:z.string().nullable().optional(),taskId:z.string().nullable().optional(),page:z.string().nullable().optional()}).optional()}); app.post('/api/chat',schema(chatBody),async(req,res,next)=>{try{send(res,await agent.chat(req.body))}catch(e){next(e)}}); app.post('/api/agent/approvals/:id/approve',async(req,res,next)=>{try{send(res,await agent.approve(req.params.id))}catch(e){next(e)}}); app.post('/api/agent/approvals/:id/reject',async(req,res,next)=>{try{send(res,await agent.reject(req.params.id))}catch(e){next(e)}});
app.use((err:any,_req:any,res:any,_next:any)=>res.status(err.status??500).json({data:null,error:err.message??'服务器错误'}));
